import {
  NLCItem,
  Sale,
  InventoryItem,
  PurchaseOrder,
  RetailerProfile
} from "../types";

/**
 * FRONTEND-ONLY STUB FILE
 * ----------------------------------
 * All AI / Gemini logic will live in backend (Cloud Run).
 * Frontend will only call APIs.
 */

/**
 * Stub: Parse NLC data
 * Backend will implement actual logic later
 */
export const parseNLCData = async (
  rawText: string
): Promise<Partial<NLCItem>[]> => {
  // TODO: Replace with backend API call
  return [];
};

/**
 * Stub: Generate business insights
 * Backend will implement actual Gemini logic later
 */
export const generateBusinessInsights = async (
  nlcData: NLCItem[],
  salesData: Sale[],
  inventory: InventoryItem[],
  retailerProfile?: RetailerProfile
): Promise<string> => {
  // TODO: Replace with backend API call
  return "Business insights will be generated by backend AI service.";
};
